import { Language, TranslationDictionary } from './types';

export const TRANSLATIONS: TranslationDictionary = {
  [Language.EN]: {
    'nav.home': 'Roadmap',
    'nav.models': 'Models',
    'nav.compare': 'Compare',
    'nav.ai': 'AI Engine',
    'roadmap.hero.title': 'Building the Future of Motorcycle Intelligence',
    'roadmap.hero.subtitle': 'A modular, scalable, hybrid architecture designed to revolutionize how we analyze performance, reliability, and value.',
    'roadmap.cta': 'Explore Roadmap',
    'roadmap.section.modules': 'Modular Architecture',
    'roadmap.section.timeline': 'Development Timeline',
    'roadmap.section.vision': 'Strategic Vision',
    'module.status.planned': 'Planned',
    'module.status.in_progress': 'In Progress',
    'module.status.completed': 'Completed',
    'module.status.future': 'Future Concept',
    
    // Modules
    'module.frontend.title': 'Frontend System',
    'module.frontend.desc': 'Hybrid SSR + SPA architecture for optimal SEO and dynamic user experience.',
    'module.backend.title': 'Backend API',
    'module.backend.desc': 'Scalable microservices architecture handling data normalization and logical operations.',
    'module.database.title': 'Database Core',
    'module.database.desc': 'High-performance relational data storage with optimized indexing for millions of records.',
    'module.scraper.title': 'Scraping Engine',
    'module.scraper.desc': 'Distributed multi-country data collection system with automated normalization.',
    'module.ai.title': 'AI Engine',
    'module.ai.desc': 'Gemini-powered analysis for sentiment, reliability prediction, and rider profiling.',
    'module.scoring.title': 'Scoring Matrix',
    'module.scoring.desc': 'Multi-layer algorithm combining technical specs, user reviews, and brand heritage.',
    'module.i18n.title': 'Internationalization',
    'module.i18n.desc': 'Native multi-language support from the core architecture level.',
    'module.dealer.title': 'Dealer Ecosystem',
    'module.dealer.desc': 'B2B dashboards for inventory management and market intelligence.',
    
    // Timeline
    'phase.1.title': 'Core Architecture',
    'phase.1.desc': 'Foundation setup, repo structure, and basic UI components.',
    'phase.2.title': 'Data & Scraping',
    'phase.2.desc': 'Implementation of the scraping engine and database schema.',
    'phase.3.title': 'AI Integration',
    'phase.3.desc': 'Connecting Gemini API and training the scoring models.',
    'phase.4.title': 'Marketplace',
    'phase.4.desc': 'User listing capabilities and dealer integration.',
    'phase.5.title': 'Global Expansion',
    'phase.5.desc': 'Multi-region support and advanced country filtering.',

    // Vision
    'vision.layer1.title': 'Multi-Layer Scoring',
    'vision.layer1.desc': 'We do not rely on a single metric. Our final score is a weighted aggregate of technical specs, real owner experiences, and historical brand reliability data.',
    'vision.layer2.title': 'Data Separation',
    'vision.layer2.desc': 'Official manufacturer data is immutable. User data is organic. We keep them strictly separated in the database to ensure data integrity and traceability.',
    'vision.layer3.title': 'Global First',
    'vision.layer3.desc': 'Motorcycles vary by region. Our architecture supports country-specific model variations, pricing, and availability from day one.',

    'footer.copyright': '© 2024 MOTORVERSE. All rights reserved.',
  },
  [Language.ES]: {
    'nav.home': 'Hoja de Ruta',
    'nav.models': 'Modelos',
    'nav.compare': 'Comparar',
    'nav.ai': 'Motor IA',
    'roadmap.hero.title': 'Construyendo el Futuro de la Inteligencia en Motociclismo',
    'roadmap.hero.subtitle': 'Una arquitectura híbrida, modular y escalable diseñada para revolucionar cómo analizamos el rendimiento, la fiabilidad y el valor.',
    'roadmap.cta': 'Explorar Hoja de Ruta',
    'roadmap.section.modules': 'Arquitectura Modular',
    'roadmap.section.timeline': 'Cronograma de Desarrollo',
    'roadmap.section.vision': 'Visión Estratégica',
    'module.status.planned': 'Planificado',
    'module.status.in_progress': 'En Progreso',
    'module.status.completed': 'Completado',
    'module.status.future': 'Concepto Futuro',

    // Modules
    'module.frontend.title': 'Sistema Frontend',
    'module.frontend.desc': 'Arquitectura híbrida SSR + SPA para SEO óptimo y experiencia dinámica.',
    'module.backend.title': 'API Backend',
    'module.backend.desc': 'Arquitectura de microservicios escalable que maneja normalización de datos.',
    'module.database.title': 'Núcleo de Base de Datos',
    'module.database.desc': 'Almacenamiento relacional de alto rendimiento optimizado para millones de registros.',
    'module.scraper.title': 'Motor de Scraping',
    'module.scraper.desc': 'Sistema de recolección distribuido multi-país con normalización automática.',
    'module.ai.title': 'Motor de IA',
    'module.ai.desc': 'Análisis potenciado por Gemini para sentimiento, predicción de fiabilidad y perfiles.',
    'module.scoring.title': 'Matriz de Puntuación',
    'module.scoring.desc': 'Algoritmo multicapa que combina especificaciones técnicas y reseñas reales.',
    'module.i18n.title': 'Internacionalización',
    'module.i18n.desc': 'Soporte nativo multi-idioma desde el nivel central de la arquitectura.',
    'module.dealer.title': 'Ecosistema de Distribuidores',
    'module.dealer.desc': 'Paneles B2B para gestión de inventario e inteligencia de mercado.',

    // Timeline
    'phase.1.title': 'Arquitectura Central',
    'phase.1.desc': 'Configuración base, estructura de repo y componentes UI básicos.',
    'phase.2.title': 'Datos y Scraping',
    'phase.2.desc': 'Implementación del motor de scraping y esquema de base de datos.',
    'phase.3.title': 'Integración IA',
    'phase.3.desc': 'Conexión con API Gemini y entrenamiento de modelos de puntuación.',
    'phase.4.title': 'Marketplace',
    'phase.4.desc': 'Capacidades de listado de usuarios e integración con distribuidores.',
    'phase.5.title': 'Expansión Global',
    'phase.5.desc': 'Soporte multi-región y filtrado avanzado por país.',

    // Vision
    'vision.layer1.title': 'Puntuación Multicapa',
    'vision.layer1.desc': 'No dependemos de una sola métrica. Nuestra puntuación final es un agregado ponderado de especificaciones técnicas, experiencias de propietarios y datos históricos.',
    'vision.layer2.title': 'Separación de Datos',
    'vision.layer2.desc': 'Los datos oficiales son inmutables. Los datos de usuarios son orgánicos. Los mantenemos estrictamente separados para asegurar integridad.',
    'vision.layer3.title': 'Global Primero',
    'vision.layer3.desc': 'Las motocicletas varían por región. Nuestra arquitectura soporta variaciones específicas por país, precios y disponibilidad desde el primer día.',

    'footer.copyright': '© 2024 MOTORVERSE. Todos los derechos reservados.',
  }
};
